version: '2'

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    volumes:
      # copy static files into a shared volume so the frontend can serve them
      - staticfiles:/app/staticfiles
    env_file: .env

  frontend:
    image: osmcha-frontend
    depends_on:
      - django
    volumes:
      # frontend serves django app's static files via shared volume
      - staticfiles:/srv/www/static/django
    env_file: .env

    ports:
      - "0.0.0.0:8000:80"

  redis:
    image: redis:latest

volumes:
  staticfiles:
  postgres_data:
  postgres_backup:
